### ISSUE TITLE
Cannot copy invitation

### ISSUE THREAD

**Issue by Yajo** [flathub/org.jitsi.jitsi-meet#8]
I don't know why, but recently I lost the ability to copy the link to a meeting.

Just hit any "copy" button around and you'll notice nothing gets copied to the clipboard.

I don't know if this is upstream issue or not, but I guess it should be here because those buttons still work on https://meet.jit.si on a normal browser.

**Comment by Nokia808** [comment]
I'm fully agree with the author. Just few hrs ago, I updated to last version from FlatHub & make a meeting with my students. I couldn't copy to the clipboard any thing at all ! I couldn't copy url for video room. I could not copy to clipboard at all whatever I tried !

**Comment by Yajo** [comment]
There's this workaround in the mean time:


https://user-images.githubusercontent.com/973709/109476013-52dae300-7a6e-11eb-9ac7-ef42b5bf5f0a.mp4

**Comment by ananace** [comment]
After digging some more into this, it seems like the main conference iframe is created without the permissions to read or write to clipboard, so it's perfectly understandable why it fails .
Opening the dev tools, finding the iframe, and adding `; clipboard-read; clipboard-write` to the end of the `allow` attribute makes copy work again.

If the conference you're connecting to is hosted on an older Jitsi server, then it might still work as the older method for copying to clipboard uses a hack involving a temporary text area - instead of direct clipboard access which depends on the iframe permissions.

**Comment by ananace** [comment]
Opened an upstream bug relating to the issue; https://github.com/jitsi/jitsi-meet-electron/issues/527
